// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSTWbZD6JI_dE8jITH5IGs7NgT_F56c9E',
    appId: '1:186838297135:web:087f8314e128df24aa74da',
    messagingSenderId: '186838297135',
    projectId: 'notes-3d87f',
    authDomain: 'notes-3d87f.firebaseapp.com',
    storageBucket: 'notes-3d87f.firebasestorage.app',
    measurementId: 'G-ZCGQG8KPZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabH1mofwF5skqm0EUmkuCkNlLN-Q2MJE',
    appId: '1:186838297135:android:32a01b3eb2d9a5c1aa74da',
    messagingSenderId: '186838297135',
    projectId: 'notes-3d87f',
    storageBucket: 'notes-3d87f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsg07YtBQUWkOAGEaudwNCJxHAx6f75zo',
    appId: '1:186838297135:ios:cfb2d8c44e25ca85aa74da',
    messagingSenderId: '186838297135',
    projectId: 'notes-3d87f',
    storageBucket: 'notes-3d87f.firebasestorage.app',
    androidClientId: '186838297135-vf2h31ijnsqaavbo6ll1opb930cib5ql.apps.googleusercontent.com',
    iosClientId: '186838297135-ikssrknc0me98b8lcir5qcravbq8v43d.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
