// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxe3dDjF0IcWkN61LZpWj9ZN57bLc0rLg',
    appId: '1:891860742616:web:cf23548dc94617432ec2ad',
    messagingSenderId: '891860742616',
    projectId: 'notes-75581',
    authDomain: 'notes-75581.firebaseapp.com',
    storageBucket: 'notes-75581.firebasestorage.app',
    measurementId: 'G-W8H9SXX188',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI78PORb28Gi2Rty3QiJsW44c4ObZMK04',
    appId: '1:891860742616:android:33c5cff218c628102ec2ad',
    messagingSenderId: '891860742616',
    projectId: 'notes-75581',
    storageBucket: 'notes-75581.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUA56Em8bm_H4QR_kwPNe65wMbs0pQWcw',
    appId: '1:891860742616:ios:5765e4e8c6e184852ec2ad',
    messagingSenderId: '891860742616',
    projectId: 'notes-75581',
    storageBucket: 'notes-75581.firebasestorage.app',
    iosBundleId: 'com.example.note',
  );
}